### ISSUE TITLE
Line 266 in "final data analysis code.R" doesn't work?

### ISSUE THREAD

**Issue by adamhsparks** [AGmccoy/Phytophthora-sojae-pathotype-distribution-and-fungicide-sensitivity-in-Michigan#2]
Line 266 in "final data analysis code.R" doesn't work?

https://github.com/AGmccoy/Phytophthora-sojae-pathotype-distribution-and-fungicide-sensitivity-in-Michigan/blob/78bf2437699eb0ef209f14829e5c5f3f2c6efde0/final%20data%20analysis%20code.R#L266

```r
> pathotype.adonis <- adonis(t.diversity.pathotype.jaccard ~ groups)
Error in `colnames<-`(`*tmp*`, value = colnames(lhs)) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

Or is it just my version on my machine?

**Comment by AGmccoy** [comment]
hmm, this is likely a version issue. R 3.5.2 was used for this analysis. I just ran through this .R file and was able to replicate everything on my device. Is there something you recommend to make this more accessible?

I also realized that I did not put package versions in the .R files, I will update when I can to include those

Leaving this open until I include package versions in .R files

**Comment by AGmccoy** [comment]
Package versions used for analysis have now been added to the "final data analysis code.R" file

**Comment by adamhsparks** [comment]
If you're able to reproduce it, I'd say it's likely a versioning issue. Adding the versions used should be enough. I'll admit, I'm too lazy to install all the old versions, but if you're able to reproduce it and have included the version numbers, that should be enough.

This does touch on the whole, "how reproducible is reproducible?" topic. It's a rabbit hole. You can set up a whole docker to ensure nothing like this happens, but then someone like me with an M1 Mac will likely still be unable to run it because of (current) Docker teething issues. Not much we can do about that though. But 

Anyway, thanks, version numbers is what I'd suggest and you've taken care of that.

Thank you for sharing your code and data! This helps set a good example for the plant pathology discipline.
